M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Thu 10 Apr 2025 17:25:37
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-10T17:25:37+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.762
%
G90
G05
T1
X202.55Y-117.0
X202.55Y-122.0
M30
