M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Fri 04 Apr 2025 19:33:26
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-04T19:33:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.290
%
G90
G05
T1
X133.37Y-71.6
X146.86Y-49.25
X160.34Y-71.6
M30
